### ISSUE TITLE
Fehlende xnb-Datein

### ISSUE THREAD

**Issue by XYZLassi** [tomwendel/monogameui#18]
Hallo,
eventuell ist es Sinnvoll, wenn irgendwann mal ein Release gemacht wird das benötigte Xnb-Datein mit in die Dll eigebunden werden und beibedarf extrahiert werden .

**Comment by reicheltp** [comment]
Wenn wir monogameui in ein NuGet packet stopfen, kann man ja alle benötigten XNB Files mit rein packen. (see #28)

**Comment by fnawratil** [comment]
Ich seh grad, dass das vollkommen unnötig ist. Im Projekt monogameui haben wir gar keine Assets die kompiliert werden könnten.
Solche kommen nur im Sample-Projekt vor, welches wir ja nicht in ein NuGet Packet packen würden...

Damit würde ich das als hinfällig betrachten...

**Comment by ManuelHu** [comment]
Da es keine xnb-Dateien gibt, schließe ich das hier mal.
