### ISSUE TITLE
Lizenz

### ISSUE THREAD

**Issue by af-mka** [tomwendel/monogameui#23]
Unter welcher Lizenz läuft monogameui? Darf es kommerziell genutzt werden? Schön wäre eine Lizenzdatei im repo.

**Comment by fnawratil** [comment]
@tomwendel Ich find auch, dass das Sinn macht...
Grüße, rave

**Comment by tomwendel** [comment]
Stimmt. Das hole ich doch gleich mal nach. Würde MIT nehmen. Damit kannst dus dann auch gerne kommerziell nutzen.
