### ISSUE TITLE
Kein "nuget restore" im CI-Check

### ISSUE THREAD

**Issue by fnawratil** [tomwendel/monogameui#25]
Im CI-Check wird kein Nuget restore vor dem Build aufgerufen... Deswegen schlägt er immer fehl...
Bitte ergänzen.

https://www.appveyor.com/blog/2014/03/18/about-nuget-package-restore

Mfg rave

**Comment by reicheltp** [comment]
Haha da wart ihr wieder schneller als ich. 😄 Bin noch nicht dazu gekommen das umzusetzen, werde mir aber nachher mal kurz Zeit nehmen.

**Comment by reicheltp** [comment]
Habe die CI solange ausgeschalten.
