### ISSUE TITLE
Kompatibilität mit OctoAwesome

### ISSUE THREAD

**Issue by ManuelHu** [tomwendel/monogameui#32]
- Monogame 3.5.1 (UI) <-> 3.4 (OctoAwesome)
- DesktopGL (UI) <-> WindowsDX (OctoAwesome)

Da gibts vermutlich Probleme, wenn wir das in Octo rüberholen.

**Comment by tomwendel** [comment]
mh. In AntMe! (und ein paar anderen Projekten) habe ich das Problem jetzt so gelöst, dass ich die Files aus MonoGameUI einfach ins Hauptprojekt verlinke und unter den anderen Umständen neu kompiliere. Das inkludiert dann das komplette Framework in die Assembly des Haupt-Projektes und merzt alle Abhängigkeitsprobleme aus.

MonoGameUI hat da eh noch das Problem, dass es eigentlich unterschiedliche Builds für unterschiedliche Zielplattformen brächte.

**Comment by ManuelHu** [comment]
Wir wollen ja sowieso auf engenious wechseln. Einen feature/enegenious Branch haben wir ja sowieso schon, den müsste man aktualisieren. Mit Code _verlinken_ läufts mit git dann nicht so toll. Die Dateien einfach ins Projekt inkludieren ist dann aber nicht so toll mit Updates, sollte MonoGameUi nicht auch mal auf NuGet kommen? Die neue Touch-Funktionalität ist anscheinend auch nicht in enegenious enthalten.

**Comment by tomwendel** [comment]
Der Wechsel zu Engenious führt zu Problemen bei anderen Projekten auf MonoGame Basis. Habe eine Weile drüber nachgedacht: Wie wäre es mit zwei Branches - einer auf Basis von MonoGame, einer auf Engenious. Jetzt müsste Julian beurteilen, ob der Code wirklich so weit identisch ist, dass das funktionieren könnte...?

**Comment by ManuelHu** [comment]
Wir _haben_ ja schon einen `feature/engenious`-Branch auf Basis von engenious für monogameui. Das sollte der sein, der auch für `feature/engenious` bei Octo verwendet wird. Der Branch hat den Stand vom 18. April. Dazwischen wurde ja nicht so viel großes gemacht, was nicht auf den selben Grundlagen aufbaut. Touch macht wahrscheinlich aber Probleme, das könnte man aber mit einer Build-Konstante beheben.

**Comment by tomwendel** [comment]
Im Grunde meinte ich den. Nur im Moment ist es halt noch ein Feature-Branch. Ich dachte eher an "master (MonoGame)" und "master (Engenious)" um die Kompatibilität für MonoGame aufrecht zu halten.

Und doch, es ist viel passiert. Ich habe zwischenzeitlich den ganzen Touch-Support und Drag&Drop eingebaut.

**Comment by tomwendel** [comment]
Lösung: Octo auf die aktuelle MonoGame Version gehoben. Bei Engenious müssen wir dann noch sehen...
